# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-connkl'
    subscriptionId: '1536499a-91e7-4e7d-b193-c1cbad71d769'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/KarlLayland/azurearm1/main/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/KarlLayland/azurearm1/main/parameters.json'
    overrideParameters: 
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'